networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:2::/64
  web:
    external: true

services:
  pipedfrontend:
    image: 1337kavin/piped-frontend:latest@sha256:536edde62916438da2cddced732298e6167afdf106dd096dcbd61de2570a7bfc
    restart: always
    container_name: pipedfrontend
    depends_on:
      - piped
    entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/api.piped.aosus.link/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
    networks:
      web:

  piped-proxy:
    image: 1337kavin/piped-proxy:latest@sha256:02561bd9fc37a584d5b34f20dda48d5ad761145fbf4089ae0a90e26603dfa6b6
    container_name: piped-proxy
    restart: always
    environment:
      - UDS=1
    volumes:
      - piped-proxy:/app/socket

  piped:
    image: 1337kavin/piped:latest@sha256:fd01133211e7c1914657e1d9196595ac69737e79a22af71b68ffea454c6a9d83
    container_name: piped
    restart: always
    configs:
      - source: piped
        target: /app/config.properties
    depends_on:
      - postgres
      
  nginx:
    image: nginx:mainline-alpine@sha256:5c0c2272256857e486cf9fe2983db41c0e14c72476f5ebedf474289fd9ca8627
    restart: always
    container_name: piped-nginx
    volumes:
      - piped-proxy:/var/run/ytproxy
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
      - source: pipedapi
        target: /etc/nginx/conf.d/pipedapi.conf
      - source: pipedproxy
        target: /etc/nginx/conf.d/pipedproxy.conf
      - source: pipedfrontend
        target: /etc/nginx/conf.d/pipedfrontend.conf
      - source: ytproxy
        target: /etc/nginx/snippets/ytproxy.conf
    depends_on:
      - piped
      - piped-proxy
      - pipedfrontend
    networks:
      - default
      - web

  postgres:
    image: postgres:15.7-alpine@sha256:ede3a168dae0d2154440c2b1b2c7773201bfa969d85a1859c44b6f4ab2df0ef7
    container_name: piped-postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=(piped_postgres_password)

# schedule ipv6 rotations
  ofelia:
    image: mcuadros/ofelia:latest@sha256:20da0eff4a691fed58315f27345b21496a032b578d09ba6d53a6257b5280c207
    configs:
      - source: ofelia
        target: /etc/ofelia.ini
    command: daemon --config=/etc/ofelia.ini
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

# automatically rotate IPV6 address used to comunicate with google
  smart-ipv6-rotator:
    image: quay.io/invidious/smart-ipv6-rotator@sha256:ab8ca1009d9986ffc80ba8c3115098c3d278a823599581b74cd102d49c296d8a
    container_name: smart-ipv6-rotator
    privileged: true
    userns_mode: host
    network_mode: host
    volumes:
      - /home/aosus/piped/ipv6-rotator:/tmp:rw
    command: run --ipv6range=2a03:4000:5d:b9::/64

volumes:
  postgres:
  piped-proxy:


configs:
  nginx:
    file: /home/aosus/piped/config/nginx.conf
  pipedapi:
    file: /home/aosus/piped/config/pipedapi.conf
  pipedproxy:
    file: /home/aosus/piped/config/pipedproxy.conf
  pipedfrontend:
    file: /home/aosus/piped/config/pipedfrontend.conf
  ytproxy:
    file: /home/aosus/piped/config/ytproxy.conf
  piped: 
    file: /home/aosus/piped/config.properties
  ofelia:
    file: /home/aosus/piped/ofelia.ini