networks: 
  default:
    enable_ipv6: true
  web:
    external: true

services:
  plausible_db:
    restart: unless-stopped
    image: postgres:16.4-alpine@sha256:492898505cb45f9835acc327e98711eaa9298ed804e0bb36f29e08394229550d
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=(plausible_postgres_password)

  plausible_events_db:
    restart: unless-stopped
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    volumes:
      - plausible_event-data:/var/lib/clickhouse
    configs:
      - source: clickhouse-config
        target: /etc/clickhouse-server/config.d/logging.xml
      - source: clickhouse-user-config
        target: /etc/clickhouse-server/users.d/logging.xml
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    restart: unless-stopped
    image: ghcr.io/plausible/community-edition:v2.1.1@sha256:b63e69460bfc01fee32a00b356ec76e4b1b14f17ea531e28105cb91d65d11fae
    container_name: plausible
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    expose:
      - 8000
    depends_on:
      - plausible_db
      - plausible_events_db
    # ports:
      # - 8004:8000
    environment:
      - BASE_URL=https://pa.aosus.org
      - DISALBLE_REGISTRATION=true
      - MAILER_EMAIL=plausible@services.aosus.org
      - SMTP_HOST_ADDR=smtp.eu.mailgun.org
      - SMTP_HOST_PORT=587
      - SMTP_USER_NAME=plausible@services.aosus.org
      - SECRET_KEY_BASE=(plausible_secret_key_base)
      - TOTP_VAULT_KEY=(plausible_totp_vault_key)
      - SMTP_USER_PWD=(plausible_smtp_user_pwd)
      - MAILER_ADAPTER=Bamboo.Mua
      - GOOGLE_CLIENT_ID=(plausible_google_client_id)
      - GOOGLE_CLIENT_SECRET=(plausible_google_client_secret)
      - MAXMIND_LICENSE_KEY=(plausible_maxmind_license_key)
      - MAXMIND_EDITION=GeoLite2-City
    networks:
      default:
      web:

volumes:
  geoip:
    driver: local
  postgres:
  plausible_event-data:
    external: true

configs:
  clickhouse-config:
    file: /home/aosus/plausible/clickhouse-config.xml
  clickhouse-user-config:
    file: /home/aosus/plausible/clickhouse-user-config.xml