version: "3.7"

networks:
  web:
    external: true
  discourse:
    external: true

services:
  caddy:
    image: oci.fariszr.com/fariszr/caddy-dns:cloudflare-alpine@sha256:a207d6403048832c533cce1a165e036cb506ec8327ed2c40725144c0b39a33e0
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - EMAIL=(email)
      - CLOUDFLARE_TOKEN=(cloudflare_token)
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - /home/aosus/caddy/configs:/etc/caddy/configs:ro
      - /home/aosus/caddy/proxy_error_page.html:/srv/proxy_error_page.html:ro
      - data:/data
      - config:/config
      - piped-proxy:/var/run/ytproxy
    networks:
      web:
      discourse:

configs:
  Caddyfile:
    file: /home/aosus/caddy/Caddyfile

volumes:
  data:
  config:
  piped-proxy:
    external: 
      name: piped_piped-proxy