networks:
  default:
    enable_ipv6: true
  web:
    external: true

services:
  postgres:
    image: postgres:14.12-alpine@sha256:55633b9ab4c34e2844648f9ab877b46a87c36fc3d32f06a0c7d1703360d4fa81
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=(matrix_postgres_password)
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse-postgresql:/var/lib/postgresql/data:rw
    networks:
      default:


  synapse:
    image: ghcr.io/element-hq/synapse:v1.109.0@sha256:8dfa555c4f9c469aaf3fc9704d14231647851bac692ecfcf15f7b9869a52585f
    container_name: synapse
    restart: always
    volumes:
      - synapse-media_store:/data/media_store:rw
    environment:
      - UID=991
      - GID=991
      - SYNAPSE_CONFIG_DIR=config
    configs:
      - source: synapse-homeserver
        target: /config/homeserver.yaml
        uid: "991"
        gid: "991"
      - source: synapse-log-config
        target: /config/log.config
        uid: "991"
        gid: "991"
      - source: mautrix-telegram-appservice
        target: /app-services/telegram.yaml
        uid: "991"
        gid: "991"
      - source: mautrix-discord-appservice
        target: /app-services/discord.yaml
        uid: "991"
        gid: "991"
    secrets:
      - source: matrix-signing-key
        target: signing.key
        uid: "991"
        gid: "991"
    healthcheck:
      test: [ "CMD", "curl", "-fSs", "http://localhost:8008/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      default:
      web:

  mautrix-telegram:
    container_name: mautrix-telegram
    restart: always
    image: dock.mau.dev/mautrix/telegram:v0.15.1@sha256:2091e446ac660be59427c89eea961f1355238ec41d814aa1db12dfb7a1a6dc6c
    configs:
      - source: mautrix-telegram-appservice
        target: /data/registration.yaml
      - source: mautrix-telegram-config
        target: /data/config.yaml
    networks:
      default:

  postgres-telegram:
    image: postgres:14.12-alpine@sha256:55633b9ab4c34e2844648f9ab877b46a87c36fc3d32f06a0c7d1703360d4fa81
    restart: always
    environment:
      - POSTGRES_DB=telegram
      - POSTGRES_USER=telegram
      - POSTGRES_PASSWORD=(matrix_telegram_postgres_password)
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - telegram-postgresql:/var/lib/postgresql/data:rw
    networks:
      default:

  mautrix-discord:
    container_name: mautrix-discord
    restart: always
    image: dock.mau.dev/mautrix/discord:latest@sha256:57c09ad3819abfc86e8705041b467681a7f9c59ee775a8c7002d82715d0ade7e 
    configs:
      - source: mautrix-discord-appservice
        target: /data/registration.yaml
      - source: mautrix-discord-config
        target: /data/config.yaml

  postgres-discord:
    image: postgres:14.12-alpine@sha256:55633b9ab4c34e2844648f9ab877b46a87c36fc3d32f06a0c7d1703360d4fa81
    restart: always
    environment:
      - POSTGRES_DB=discord
      - POSTGRES_USER=discord
      - POSTGRES_PASSWORD=(matrix_discord_postgres_password)
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - discord-postgres:/var/lib/postgresql/data:rw

# Discord now requires signed URLs for their CDN, this resolver fetches signed urls using a user token, and redirects the user to it.
  discord-resolver:
    image: ghcr.io/aosus/discord_cdn:master@sha256:7f3ac0ff060c4fb44e8caeac9e26f80a8d0056ba0e1012b4c2184b3b11a6099d
    # ports:
    #   - 3000:3000
    environment:
      - TOKEN=(matrix_discord_resolver_account_token)
      - CACHE=86400 # cache discord links for a day
    networks:
      - web

  eturnal:
    image: ghcr.io/processone/eturnal:edge@sha256:bef774e503eed347fadbaeb1e9a1829e044355129d8fa83954ecf990bd23d559
    user: 0:0 # to access caddy certs
    ports:
      - '3478:3478'
      - '32000-32200:32000-32200'
      - '3478:3478/udp'
      - '32000-32200:32000-32200/udp'
    volumes:
      - caddy_data:/caddy-data:ro
    environment:
      - ETURNAL_USER=root
    configs:
      - source: eturnal
        target: /etc/eturnal.yml

  postgres-sync:
    image: postgres:15.7-alpine@sha256:ede3a168dae0d2154440c2b1b2c7773201bfa969d85a1859c44b6f4ab2df0ef7
    restart: always
    # These will be used in homeserver.yaml later on
    environment:
      - POSTGRES_DB=sync
      - POSTGRES_USER=sync
      - POSTGRES_PASSWORD=(MATRIX_SLIDING_SYNC_POSTGRES_PASSWORD)
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - sliding-sync-postgres:/var/lib/postgresql/data
    networks:
      default:

  sliding-sync:
    image: ghcr.io/matrix-org/sliding-sync:v0.99.18@sha256:a133def6de9182fd3047097137a7f2b7c3ff4d1cded92a4d622c359504939aa6
    restart: always
    environment:
      - SYNCV3_SERVER=https://matrix.aosus.org
      - SYNCV3_DB=(MATRIX_SLIDING_SYNC_POSTGRES_CONNECTION_STRING)
      - SYNCV3_SECRET=(MATRIX_SLIDING_SYNC_SECRET)
    depends_on:
      - postgres-sync
      - synapse
    networks:
      web:
      default:

configs:
  synapse-homeserver:
    file: /home/aosus/matrix/homeserver.yaml
  synapse-log-config:
    file: /home/aosus/matrix/log.config
  mautrix-telegram-appservice:
    file: /home/aosus/matrix/mautrix-telegram/app-service-registration.yaml
  mautrix-telegram-config:
    file: /home/aosus/matrix/mautrix-telegram/config.yaml
  mautrix-discord-config:
    file: /home/aosus/matrix/mautrix-discord/config.yaml
  mautrix-discord-appservice:
    file: /home/aosus/matrix/mautrix-discord/app-service-registration.yaml
  eturnal:
    file: /home/aosus/matrix/eturnal.yml
# import key using file created by github runner.
secrets:
  matrix-signing-key:
    file: /home/aosus/matrix/signing.key

volumes:
  caddy_data:
    external: true
  synapse-postgresql:
  synapse-media_store:
  telegram-postgresql:
  discord-postgres:
  sliding-sync-postgres: