networks: 
  default:
    enable_ipv6: true
  web:
    external: true

services:
  wordpress:
    image: wordpress:6.6.1-apache@sha256:c029a137bec0b344fc1ced1980d12a82b93aae9105240afd4e3b1bf83d79a618
    container_name: aosus-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: aosusworddb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: (aosus_wordpress_mariadb_password)
      # WORDPRESS_DEBUG: true
    networks: 
      default:
      web:
    volumes:
      - html:/var/www/html:rw
    configs:
      - source: custom-ini
        target: /usr/local/etc/php/conf.d/custom.ini

  mariadb:
    image: mariadb:11.5.2@sha256:4b812bbd9a025569fbe5a7a70e4a3cd3af53aa36621fecb1c2e108af2113450a
    restart: always
    environment:
      MARIADB_USER: aosusworddb
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD: (aosus_wordpress_mariadb_password)
      MARIADB_AUTO_UPGRADE: true
      #MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_ROOT_PASSWORD: (aosus_wordpress_mariadb_root_password)
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
  html:

configs:
  custom-ini:
    file: /home/aosus/aosus-wordpress/custom.ini
