networks: 
  default:
    enable_ipv6: true
  web:
    external: true

services:
  wordpress:
    image: wordpress:6.5.2-apache@sha256:a0fe883211001f2425a63d7630b89b5388a792631b0c74840855bbf5a6700562
    container_name: aosus-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: aosusworddb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: (aosus_wordpress_mariadb_password)
      # WORDPRESS_DEBUG: true
    networks: 
      default:
      web:
    volumes:
      - html:/var/www/html:rw
    configs:
      - source: custom-ini
        target: /usr/local/etc/php/conf.d/custom.ini

  mariadb:
    image: mariadb:11.2.3@sha256:c4bca6ff417cdfcaf9a4bf2fd459b5f5c03380b123363eaeae7bf2c1d9097d18
    restart: always
    environment:
      MARIADB_USER: aosusworddb
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD: (aosus_wordpress_mariadb_password)
      MARIADB_AUTO_UPGRADE: true
      #MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_ROOT_PASSWORD: (aosus_wordpress_mariadb_root_password)
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
  html:

configs:
  custom-ini:
    file: /home/aosus/aosus-wordpress/custom.ini
