networks: 
  default:
    enable_ipv6: true
  web:
    external: true

services:
  wordpress:
    image: wordpress:6.5.3-apache@sha256:17e2fcbed748aebc7627d62f768899bacaa50ef8094e43c6e256b58519680f28
    container_name: aosus-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: aosusworddb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: (aosus_wordpress_mariadb_password)
      # WORDPRESS_DEBUG: true
    networks: 
      default:
      web:
    volumes:
      - html:/var/www/html:rw
    configs:
      - source: custom-ini
        target: /usr/local/etc/php/conf.d/custom.ini

  mariadb:
    image: mariadb:11.2.3@sha256:0f0a49c44b7603ccc35c2828be9ce9febb3ef0cf5975ba7ecfabb3a3ec4cdcdb
    restart: always
    environment:
      MARIADB_USER: aosusworddb
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD: (aosus_wordpress_mariadb_password)
      MARIADB_AUTO_UPGRADE: true
      #MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_ROOT_PASSWORD: (aosus_wordpress_mariadb_root_password)
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
  html:

configs:
  custom-ini:
    file: /home/aosus/aosus-wordpress/custom.ini
