networks: 
  default:
    enable_ipv6: true
  web:
    external: true

services:
  wordpress:
    image: wordpress:6.5.2-apache@sha256:269570d7c2e829b583f808dc1089ce6369aa9e7b4e9f4f596409d6a26c483d46
    container_name: aosus-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: aosusworddb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: (aosus_wordpress_mariadb_password)
      # WORDPRESS_DEBUG: true
    networks: 
      default:
      web:
    volumes:
      - html:/var/www/html:rw
    configs:
      - source: custom-ini
        target: /usr/local/etc/php/conf.d/custom.ini

  mariadb:
    image: mariadb:11.2.3@sha256:a4880d35a4284659897692f5871a6fcf1e0802bc33f7279f403f9038bd999081
    restart: always
    environment:
      MARIADB_USER: aosusworddb
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD: (aosus_wordpress_mariadb_password)
      MARIADB_AUTO_UPGRADE: true
      #MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_ROOT_PASSWORD: (aosus_wordpress_mariadb_root_password)
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
  html:

configs:
  custom-ini:
    file: /home/aosus/aosus-wordpress/custom.ini
